### ISSUE TITLE
UUID cannot be used for Span ID

### ISSUE THREAD

**Issue by prodjito** [newrelic/newrelic-telemetry-sdk-java#186]
In SpanExample.java and TelemetryClientExample.java, UUID is used for Span IDs. 

For example,
https://github.com/newrelic/newrelic-telemetry-sdk-java/blob/master/telemetry_examples/src/main/java/com/newrelic/telemetry/examples/SpanExample.java#L55

UUID is 16 bytes. It is just the right length for Trace ID but it is too long for Span ID, which should be 8 bytes. Trace context with an invalid Span ID will have interoperability issues because downstream services instrumented by a different vendor will ignore the trace context.

**Comment by breedx-nr** [comment]
So according to [our docs for the Trace API](https://docs.newrelic.com/docs/understand-dependencies/distributed-tracing/trace-api/report-new-relic-format-traces-trace-api), there isn't a predefined length for span IDs.  It's just an id.

Perhaps you're trying to suggest that because W3C trace context `parent-id` (`span-id`) is just 8 bytes that ours should be restricted as well?

In any case, I think we are confirming to the requirements of our ingest endpoint, and I'd like to close this unless you have a practical suggestion about how to improve the current situation.  Simply suggesting that "Span ID should be 8 bytes" isn't really completely accurate.  If the application is processing W3C compliant spans, then that is true...but there could be users of this SDK that are explicitly _not_ handling W3C compliant span IDs.

Make sense?  Mind if we close this?

**Comment by prodjito** [comment]
Yes, that makes sense. Thank you!
