### ISSUE TITLE
Assistance in querying data 

### ISSUE THREAD

**Issue by saarthakgupta** [newrelic/newrelic-telemetry-sdk-java#254]
Hello,

let me please start by apologizing for posting this here as an issue. I'm fairly new to the NewRelic world and couldn't figure out a better place to ask my doubt. Sincere apologies. 

I use maven to build my projects and I've added Dropwizard Metrics + NR's telemetry SDK to report my application's metrics to NR. I am able to see the data being reported in the Insights alright. However, what I want now is to plot the graph based on the `count` of my metrics. I have reported `Guage` type data, but I'm unable to figure out how to write an NRQL statement to plot this data. I've attached a screenshot of how my data looks. 

Any help in this is highly appreciated. Again, apologies for posting this here.

Thank you in advance for your help.
<img width="1179" alt="Screenshot 2020-11-11 at 02 10 41" src="https://user-images.githubusercontent.com/7579616/98731195-5d8c4200-23c3-11eb-9f92-d8e99a86f377.png">

**Comment by XiXiaPdx** [comment]
Hello @saarthakgupta!  I understand how difficult it can be to find an answer when there is so much to look through.  I believe this document will help you start visualizing your data.  

https://docs.newrelic.com/docs/telemetry-data-platform/get-data/apis/query-metric-data-type#view-and-query

From the image you provided, I'm guessing you'll want to start with a query like this:

`SELECT count(`Doctor Portal something`) FROM Metric TIMESERIES` 

The following are future resources I suggest you try with NRQL questions because this is where the real experts live 😉 

We have a very active user community dedicated to answering questions regarding all the tricks of NRQL.

https://discuss.newrelic.com/c/build-on-new-relic/data-queries

Finally, some smart people put together a graduated learning series to learn NRQL with real data! If you like to learn with hands-on practice from a curated experienced, I recommend it. 

https://opensource.newrelic.com/projects/newrelic/nr1-learn-nrql

**Comment by saarthakgupta** [comment]
Thank you @XiXiaPdx . I will look into these and move ahead. have a great day!
