### ISSUE TITLE
Telemetry SDK does not support Metrics API v2

### ISSUE THREAD

**Issue by Sidburse** [newrelic/newrelic-telemetry-sdk-java#284]
According to https://docs.newrelic.com/docs/apis/rest-api-v1-deprecated/new-relic-rest-api-v1/working-new-relic-rest-api-v1-deprecated/ , Metric API v1 seems to be deprecated. 
Is there a client to support [Metric v2 API](https://docs.newrelic.com/docs/apis/rest-api-v2/get-started/introduction-new-relic-rest-api-v2/) in Telemetry SDK?

**Comment by kford-newrelic** [comment]
@Sidburse thanks for raising this issue/question.

You are correct on the version of the API our Telemetry SDK uses but we do not have plans at this time to update it (which isn't a problem, since we have no plans to terminate the v1 API yet).

Is there a particular problem that this causes for you or are you just inquiring?

**Comment by Sidburse** [comment]
@kford-newrelic No, this isn't causing any problem, was just inquiring. Thank you for the clarification.
