### ISSUE TITLE
Need to upgrade OKHTTP versions

### ISSUE THREAD

**Issue by edyu002** [newrelic/newrelic-telemetry-sdk-java#316]
Snyk scan of newrelic-telemetry-sdk-java is reporting com.squareup.okhttp3:okhttp@4.9.0 vulnerabilities. 
https://security.snyk.io/package/maven/com.squareup.okhttp3:okhttp/4.9.0

Request to upgrade com.squareup.okhttp3 to a non-vulnerable version.

**Comment by meiao** [comment]
![image](https://github.com/newrelic/newrelic-telemetry-sdk-java/assets/292463/10621254-8854-4e44-b8fa-b2306010dca7)
Unfortunately, there is no version of kotlin-stdlib that has a fix.

As a workaround if you are using Java 11+ you can use `com.newrelic.telemetry:telemetry-http-java11` instead of `com.newrelic.telemetry:telemetry-http-okhttp`.
You'd also have to change the TelemetryClient initialization code to use the other provider.

**Comment by edyu002** [comment]
Thanks for the reply. Unfortunately, our product New Relic monitoring for
SAP is targeting SAP environments, which still use java 8. I read somewhere
that OKHttp 5.0 stopped using the kotline library and this issue is fixed.
However, it looks like OKHttp 5.0 is still in alpha release stage. Do we
have any plans to go to OkHttp5.0?

Best
--Ed Yu

**Comment by meiao** [comment]
When it is GA.
