### ISSUE TITLE
put the gson classes into their original com.google.gson.stream package

### ISSUE THREAD

**Issue by jkwatson** [newrelic/newrelic-telemetry-sdk-java#72]

**Comment by wpoch** [comment]
Hi, which was the intention while doing this? 
By moving the class to the original package make it conflict with the REAL class from the Gson package, so for example if I'm using Gson `2.3.1` the `jsonValue` doesn't exists, giving runtime errors, because the class you are using is in the same package of the already loaded one.

I think moving the class to the original package instead of your own, makes things more complicated.

**Comment by jkwatson** [comment]
I believe the intention was to make it simpler to keep the classes up to date. I think @breedx-nr originally asked for it. However, if this is causing issues, then I don't think there's a particular strong reason not to relocate them.  What do you think @breedx-nr ?

**Comment by breedx-nr** [comment]
There were two original intentions: 
1. Not have google classes moved into a `com.newrelic` package because it's misleading and somewhat misrepresentative.
2. Be able to automate license headers across the source tree (com.newrelic) without having to make onsey-twosey exceptions for non-NR classes that got brought into our namespace.
Moving them is fine (feel free to PR that), but we'll have to address license header automation if we do that.

**Comment by wpoch** [comment]
Thank you both for the context, I created: https://github.com/newrelic/newrelic-telemetry-sdk-java/pull/148

That will work for the short term, but maybe you can see if adding a shadow plugin makes sense.
